"""initial_schema_with_all_tables

Revision ID: 265f97ab88c1
Revises: 
Create Date: 2025-10-31 18:09:05.630804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '265f97ab88c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_configuracao', sa.String(length=100), nullable=False),
    sa.Column('servidor_smtp', sa.String(length=255), nullable=False),
    sa.Column('porta_smtp', sa.Integer(), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('email_remetente', sa.String(length=255), nullable=False),
    sa.Column('nome_remetente', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('template_assunto', sa.String(length=500), nullable=True),
    sa.Column('template_corpo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_configuracao')
    )
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('is_developer', sa.Boolean(), nullable=True),
    sa.Column('primeiro_login', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('cor_agenda', sa.String(length=7), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('legendas_predefinidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('tipo_obra', sa.String(length=100), nullable=False),
    sa.Column('construtora', sa.String(length=200), nullable=False),
    sa.Column('nome_funcionario', sa.String(length=200), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('email_principal', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_previsao_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('numeracao_inicial', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('relatorios_express',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('empresa_nome', sa.String(length=200), nullable=False),
    sa.Column('empresa_endereco', sa.Text(), nullable=True),
    sa.Column('empresa_telefone', sa.String(length=20), nullable=True),
    sa.Column('empresa_email', sa.String(length=120), nullable=True),
    sa.Column('empresa_responsavel', sa.String(length=200), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('data_visita', sa.Date(), nullable=False),
    sa.Column('periodo_inicio', sa.Time(), nullable=True),
    sa.Column('periodo_fim', sa.Time(), nullable=True),
    sa.Column('condicoes_climaticas', sa.String(length=200), nullable=True),
    sa.Column('temperatura', sa.String(length=50), nullable=True),
    sa.Column('checklist_completo', sa.Text(), nullable=True),
    sa.Column('checklist_dados', sa.Text(), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('pendencias', sa.Text(), nullable=True),
    sa.Column('recomendacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('endereco_visita', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('finalizado_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('user_email_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('email_password', sa.Text(), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('aprovadores_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('aprovador_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprovador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'aprovador_id', name='unique_aprovador_projeto')
    )
    op.create_table('categorias_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('nome_categoria', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'nome_categoria', name='uq_categoria_por_projeto')
    )
    op.create_table('checklist_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'ordem', name='unique_ordem_por_projeto')
    )
    op.create_table('contatos_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=False),
    sa.Column('tipo_relacionamento', sa.String(length=100), nullable=True),
    sa.Column('is_aprovador', sa.Boolean(), nullable=True),
    sa.Column('receber_relatorios', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nome_contato', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('receber_notificacoes', sa.Boolean(), nullable=True),
    sa.Column('receber_relatorios', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'email', name='unique_email_por_projeto')
    )
    op.create_table('fotos_relatorios_express',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_express_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filename_original', sa.String(length=255), nullable=True),
    sa.Column('filename_anotada', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('legenda', sa.String(length=500), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('local', sa.String(length=300), nullable=True),
    sa.Column('anotacoes_dados', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('coordenadas_anotacao', sa.Text(), nullable=True),
    sa.Column('imagem', sa.LargeBinary(), nullable=True),
    sa.Column('imagem_hash', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('imagem_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_express_id'], ['relatorios_express.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome_funcionario', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('is_responsavel_principal', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'user_id', name='unique_funcionario_por_projeto')
    )
    op.create_table('projeto_checklist_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_checklist', sa.String(length=20), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_table('reembolsos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fim', sa.Date(), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=True),
    sa.Column('valor_km', sa.Float(), nullable=True),
    sa.Column('alimentacao', sa.Float(), nullable=True),
    sa.Column('hospedagem', sa.Float(), nullable=True),
    sa.Column('outros_gastos', sa.Float(), nullable=True),
    sa.Column('descricao_outros', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('aprovado_por', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_express_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_express_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relatorio_express_id'], ['relatorios_express.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('projeto_outros', sa.String(length=300), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('data_realizada', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('atividades_realizadas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('endereco_gps', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_pessoal', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunicacoes_visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('numero_projeto', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('aprovador_id', sa.Integer(), nullable=True),
    sa.Column('data_relatorio', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('checklist_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('comentario_aprovacao', sa.Text(), nullable=True),
    sa.Column('acompanhantes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lembrete_proxima_visita', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprovador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'numero', name='uq_relatorios_projeto_numero')
    )
    op.create_table('visita_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visita_id', 'user_id', name='unique_visita_participante')
    )
    op.create_table('envios_relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('email_destinatario', sa.String(length=120), nullable=False),
    sa.Column('nome_destinatario', sa.String(length=200), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('status_entrega', sa.String(length=50), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=True),
    sa.Column('erro_envio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filename_original', sa.String(length=255), nullable=True),
    sa.Column('filename_anotada', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('legenda', sa.String(length=500), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('local', sa.String(length=300), nullable=True),
    sa.Column('anotacoes_dados', sa.JSON(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('coordenadas_anotacao', sa.JSON(), nullable=True),
    sa.Column('imagem', sa.LargeBinary(), nullable=True),
    sa.Column('imagem_hash', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('imagem_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_envio_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('destinatarios', sa.Text(), nullable=False),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('bcc', sa.Text(), nullable=True),
    sa.Column('assunto', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('erro_detalhes', sa.Text(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usuario_origem_id', sa.Integer(), nullable=True),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('link_destino', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lida_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('email_enviado', sa.Boolean(), nullable=True),
    sa.Column('email_sucesso', sa.Boolean(), nullable=True),
    sa.Column('email_erro', sa.Text(), nullable=True),
    sa.Column('push_enviado', sa.Boolean(), nullable=True),
    sa.Column('push_sucesso', sa.Boolean(), nullable=True),
    sa.Column('push_erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usuario_origem_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('log_envio_emails')
    op.drop_table('fotos_relatorio')
    op.drop_table('envios_relatorios')
    op.drop_table('visita_participantes')
    op.drop_table('relatorios')
    op.drop_table('comunicacoes_visitas')
    op.drop_table('checklist_items')
    op.drop_table('visitas')
    op.drop_table('relatorio_express_participantes')
    op.drop_table('reembolsos')
    op.drop_table('projeto_checklist_config')
    op.drop_table('funcionarios_projetos')
    op.drop_table('fotos_relatorios_express')
    op.drop_table('emails_clientes')
    op.drop_table('contatos_projetos')
    op.drop_table('checklist_obra')
    op.drop_table('categorias_obra')
    op.drop_table('aprovadores_padrao')
    op.drop_table('user_email_config')
    op.drop_table('relatorios_express')
    op.drop_table('projetos')
    op.drop_table('legendas_predefinidas')
    op.drop_table('users')
    op.drop_table('tipos_obra')
    op.drop_table('contatos')
    op.drop_table('configuracao_email')
    op.drop_table('checklist_templates')
    op.drop_table('checklist_padrao')
    # ### end Alembic commands ###