"""Adicionar novos campos em Relatorio e FotoRelatorio conforme especificacao tecnica

Revision ID: fe8e8e8ec755
Revises: cc5ad1eaca6b
Create Date: 2025-11-02 02:42:45.664395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'fe8e8e8ec755'
down_revision = 'cc5ad1eaca6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Verificar e adicionar colunas na tabela fotos_relatorio
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    fotos_columns = [col['name'] for col in inspector.get_columns('fotos_relatorio')]
    with op.batch_alter_table('fotos_relatorio', schema=None) as batch_op:
        if 'acompanhantes' not in fotos_columns:
            batch_op.add_column(sa.Column('acompanhantes', sa.Text(), nullable=True))

    # Verificar e adicionar colunas na tabela relatorios
    relatorios_columns = [col['name'] for col in inspector.get_columns('relatorios')]
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        if 'descricao' not in relatorios_columns:
            batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        if 'observacoes_gerais' not in relatorios_columns:
            batch_op.add_column(sa.Column('observacoes_gerais', sa.Text(), nullable=True))
        if 'condicoes_climaticas' not in relatorios_columns:
            batch_op.add_column(sa.Column('condicoes_climaticas', sa.String(length=100), nullable=True))
        if 'temperatura' not in relatorios_columns:
            batch_op.add_column(sa.Column('temperatura', sa.String(length=50), nullable=True))
        if 'acompanhantes' not in relatorios_columns:
            batch_op.add_column(sa.Column('acompanhantes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Verificar colunas antes de remover
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    relatorios_columns = [col['name'] for col in inspector.get_columns('relatorios')]
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        if 'acompanhantes' in relatorios_columns:
            batch_op.drop_column('acompanhantes')
        if 'temperatura' in relatorios_columns:
            batch_op.drop_column('temperatura')
        if 'condicoes_climaticas' in relatorios_columns:
            batch_op.drop_column('condicoes_climaticas')
        if 'observacoes_gerais' in relatorios_columns:
            batch_op.drop_column('observacoes_gerais')
        if 'descricao' in relatorios_columns:
            batch_op.drop_column('descricao')

    fotos_columns = [col['name'] for col in inspector.get_columns('fotos_relatorio')]
    with op.batch_alter_table('fotos_relatorio', schema=None) as batch_op:
        if 'acompanhantes' in fotos_columns:
            batch_op.drop_column('acompanhantes')

    # ### end Alembic commands ###